def main():

    # io exception
    #  try:
    #     df = open("kal.txt", "r")
    #     st = "i am wriing"
    #     df.write(st)
    #     df.close()
    #  except IOError as e:
    #      print "file not found"
    #      print (e)
    #      print (e.errno)
    #
    # # raise exception
    #  try:
    #     df = open("kal.txt", "r")
    #     st = "i am wriing"
    #     df.write(st)
    #     df.close()
    #
    #  except Exception as e:
    #      print ('file not found')
    #  raise

    # name exception
    #  try:
        input_variable = int(raw_input("enter your name"))
        print ("your name is " + input_variable)
     # except ValueError:
     #     print ("user input has name error")















if __name__== "__main__" :main()